### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by MoritzHayden** [MoritzHayden/bosco#10]
Add unit tests with [pytest](https://pypi.org/project/pytest/) for the following in the [src/tests](https://github.com/MoritzHayden/bosco/tree/main/src/tests) directory:

- [x] [service/drg.py](https://github.com/MoritzHayden/bosco/blob/main/src/service/drg.py)
- [x] [util/date.py](https://github.com/MoritzHayden/bosco/blob/main/src/util/date.py)

**Comment by hynrey** [comment]
How can we add pytest to Run Pylint Action?
Sorry for spaming with refs. I realized that some fixes are better not to ref to issue.

**Comment by MoritzHayden** [comment]
> How can we add pytest lib to dev dependencies to pass Pylint Action? I fixed whitespace trailing and redefining name from outer scope when using pytest fixtures. Sorry for spaming with refs. I realized that some fixes are better not to ref to issue.

I've added Pytest to the dev dependencies in the Pipfile and created a new GitHub workflow that requires the Pytests to pass before a PR is merged. I've also added a few basic tests for the utils. Please take a look and rebase your branch with main. Thank you!
