### ISSUE TITLE
Add slash commands to Bosco's BIO

### ISSUE THREAD

**Issue by hynrey** [MoritzHayden/bosco#5]
### Feature
Add slash commands to  Bosco's **BIO** for quick recall of commands without having to type them.
Not to be confused with **"try my commands"** section, because the bot must be verified (be on 70+ servers) in order to use it.

### Implementation

To do this, in the Discord Developer Portal, add commands and their IDs to the bot description. To get ID of command needs to type command and then click on it with right mouse button and copy ID

![copy](https://i.imgur.com/2HwIvfc.png)

Example:
`</(command-name):(command-ID)>`

```
**TRY MY COMMANDS**

</play:938016496168932622> | </help:938012345242127927>
```
![example](https://i.imgur.com/D518w1Z.png)

**Comment by MoritzHayden** [comment]
Great idea! Thank you for the suggestion. I've updated Bosco's bio with this and provided a screenshot below. I've also provided a table of the command IDs for reference.

## Command IDs

| Command | ID |
|--------|--------|
| /ping | 1097671435608133692 |
| /deep-dive | 1098257410159812628 |
| /rock-and-stone | 1098359333269549116 |
| /trivia | 1099109191811092591 |
| /invite | 1098660880234860635 | 
| /help | 1098384804933812324 |

## Bio Screenshot
![Bosco Bio](https://user-images.githubusercontent.com/31516660/233809003-84641294-ee01-43fb-a566-a38c87237413.png)
